### ISSUE TITLE
Is the commit reveal correct?

### ISSUE THREAD

**Issue by flockonus** [joelsfoster/rock-paper-scissors#21]
I was reading though this article https://karl.tech/learning-solidity-part-2-voting/

I was reading over your implementation, but it seems the password is being exposed, have you considered this?

**Comment by joelsfoster** [comment]
Hi @flockonus! You do bring up a good point that the password in Karl's example is hashed on the front end, and the hashed password is submitted into the smart contract function, whereas in my app I took their raw password string and sent it in the transaction to the smart contract, where I hashed it and stored it. This is indeed a security flaw, because the raw exposed data is visible in the transaction. This is less of a problem with the password, but more so a problem because the player's move is revealed. Thanks for pointing this out! I think I'll fix it by following Karl's implementation:

1) On the front end, I'll hash the combination of the user's password and move.
2) Then I'll send that hash to the contract and store it.
3) For the reveal, the user will resubmit the password+move combination.
4) If the hash of those two matches the stored hash, I'll store the raw move in the contract and use it to determine the winner.

**Comment by rstormsf** [comment]
I came to this repo from https://medium.com/coinmonks/common-attacks-in-solidity-and-how-to-defend-against-them-9bc3994c7c18

and also noticed the security flaw. 
You should accept only the hashed value.

**Comment by rstormsf** [comment]
you should check out zkSnarks to make it more robust

**Comment by joelsfoster** [comment]
Thanks @flockonus and @rstormsf! In my efforts to ship out a functional DApp before the project's submission deadline, and by focusing too much on Solidity security, I failed to recognize this rather simple front end vulnerability. To fix it, I implemented encryption on the front end so moves and password hashes are submitted to the contract as a single encryptedMove hash. In the reveal phase, the revealed values (the exposed move value and the password hash) are submitted to the contract, which then validates that their combined keccak256 hash matches the original encrypted move hash they submitted. 

[#23 "Now encrypts commit/reveal data on the front end before transmitting to the blockchain"](https://github.com/joelsfoster/rock-paper-scissors/pull/23)
